### ISSUE TITLE
doesn't reject codepoints over U+10FFFF

### ISSUE THREAD

**Issue by graphitemaster** [skeeto/branchless-utf8#3]
It does appear to handle overlong encodings through the use of the minimum table but sequences starting from 0x110000 and up are incorrectly handled instead of rejected. This is easier understood since it must accept a lead byte of the values in that range (since byte 0xF4 is valid), however there is no logic for rejecting the invalid encodings starting with that byte, for which there are many.

**Comment by skeeto** [comment]
Thanks, you were right. This check comes at a pretty big performance 
penalty, and I can't think of a more efficient way to do it.
